language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install build-essential curl file git
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - sudo apt-get -y install libxml2-dev
  - test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
  - test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
  - test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
  - echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
  
install:
  - brew install pipenv
  - pipenv install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE unblocker;" -U postgres
  - psql -c "CREATE USER n WITH PASSWORD '123456' createdb;" -U postgres

script:
  - pytest
  - pytest --cov

after_success:
  - coveralls