language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install build-essential curl file git
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - sudo apt-get -y install libxml2-dev
 
  
install:
  - brew install pipenv
  - pipenv install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE unblocker;" -U postgres
  - psql -c "CREATE USER n WITH PASSWORD '123456' createdb;" -U postgres

script:
  - pytest
  - pytest --cov

after_success:
  - coveralls