language: python
python:
  - "3.6"
  
install:
  - pip install flask
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE ireporterflask;" -U postgres
  - psql -c "CREATE USER n WITH PASSWORD '123456' createdb;" -U postgres

script:
  - pytest --cov

after_success:
  - coveralls