language: python
python:
  - "3.6"

before_install:
  - pip install pipenv
  - pipenv shell
 
  
install:
  - pipenv install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE unblocker;" -U postgres
  - psql -c "CREATE USER n WITH PASSWORD '123456' createdb;" -U postgres

script:
  - pytest
  - pytest --cov

after_success:
  - coveralls