language: python
python:
- '3.6'
before_install:
- pip install pipenv
install:
- pipenv install
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE unblocker;" -U postgres
- psql -c "CREATE USER n WITH PASSWORD '123456' createdb;" -U postgres
script:
- pytest
- pytest --cov
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: A5okkOl83KV2lWroD5k4axXS0m4moX0z/+PmQgfF0ZWNhwOW3ra9klMhD1F5MoSkBQSHJqAsrtKSFzpTQWE0v2olyqGGsDZN47Mq4IBa91SAG7grNIdRbWOsIQx8/lLO6rYFwfrGkXByAwszhgB5paWBr965EeCgFhcsGmSyg7CdwYYitr+nCoYGZySTjav4xVg5GRlG8GCeDo3GbD9/BSqKniOMzd6+ciwbBvumUibQiI4BM2j/Pi08tQUNp94z98AFoRKFpn2VLqpzdCEvAQeY9FVdr3ie8Zz14SNBL95cgDtXYdNi0trFZZPF/Bg1MQ07hTByOgT5z38fRtv+3eps/G81XMhu5jLDS/e1ABDXpp4VeleGgcse8eUc7UbJLLSmr3yD+X5uytK033IZfgeyok8Meu5vat3P4S2RpbnIupW1H1RLhDbjdFodTkki0llULIGRe1BVboKEZ1IrKdsva6CKGK56Rxy2BLZqlo5fLAM8wBvnVn7GjjPjB6Z/X37DTjTNhvwYAwVYAMoH0gpc/HK0xPFThssq+ncMIBEkqKjm8rNMVqHiGgnu9hiYob9iGyGITeZoVRaJH59OBGKkG87rDoGM00CeD2wV9PecZFM4dyV8mCUqBxjsdvYnDOQ1VozaFTzXNi57YQxGq6Gef3jmhQjv0AtR0qp21YI=
  on: develop
