language: python
python:
  - "3.6"
  
install:
  - pip install pipenv

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE unblocker;" -U postgres
  - psql -c "CREATE USER n WITH PASSWORD '123456' createdb;" -U postgres

script:
  - pipenv shell
  - pipenv install
  - pytest --cov

after_success:
  - coveralls